/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TinTucRouteImport } from './routes/tin-tuc'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as DuAnRouteImport } from './routes/du-an'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SanPhamIndexRouteImport } from './routes/san-pham.index'
import { Route as DichVuIndexRouteImport } from './routes/dich-vu.index'
import { Route as SanPhamSlugRouteImport } from './routes/san-pham.$slug'
import { Route as DichVuSlugRouteImport } from './routes/dich-vu.$slug'

const TinTucRoute = TinTucRouteImport.update({
  id: '/tin-tuc',
  path: '/tin-tuc',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const DuAnRoute = DuAnRouteImport.update({
  id: '/du-an',
  path: '/du-an',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamIndexRoute = SanPhamIndexRouteImport.update({
  id: '/san-pham/',
  path: '/san-pham/',
  getParentRoute: () => rootRouteImport,
} as any)
const DichVuIndexRoute = DichVuIndexRouteImport.update({
  id: '/dich-vu/',
  path: '/dich-vu/',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamSlugRoute = SanPhamSlugRouteImport.update({
  id: '/san-pham/$slug',
  path: '/san-pham/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DichVuSlugRoute = DichVuSlugRouteImport.update({
  id: '/dich-vu/$slug',
  path: '/dich-vu/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/du-an': typeof DuAnRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tin-tuc': typeof TinTucRoute
  '/dich-vu/$slug': typeof DichVuSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/dich-vu/': typeof DichVuIndexRoute
  '/san-pham/': typeof SanPhamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/du-an': typeof DuAnRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tin-tuc': typeof TinTucRoute
  '/dich-vu/$slug': typeof DichVuSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/dich-vu': typeof DichVuIndexRoute
  '/san-pham': typeof SanPhamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/du-an': typeof DuAnRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tin-tuc': typeof TinTucRoute
  '/dich-vu/$slug': typeof DichVuSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/dich-vu/': typeof DichVuIndexRoute
  '/san-pham/': typeof SanPhamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/du-an'
    | '/gioi-thieu'
    | '/lien-he'
    | '/sitemap.xml'
    | '/tin-tuc'
    | '/dich-vu/$slug'
    | '/san-pham/$slug'
    | '/dich-vu/'
    | '/san-pham/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/du-an'
    | '/gioi-thieu'
    | '/lien-he'
    | '/sitemap.xml'
    | '/tin-tuc'
    | '/dich-vu/$slug'
    | '/san-pham/$slug'
    | '/dich-vu'
    | '/san-pham'
  id:
    | '__root__'
    | '/'
    | '/du-an'
    | '/gioi-thieu'
    | '/lien-he'
    | '/sitemap.xml'
    | '/tin-tuc'
    | '/dich-vu/$slug'
    | '/san-pham/$slug'
    | '/dich-vu/'
    | '/san-pham/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DuAnRoute: typeof DuAnRoute
  GioiThieuRoute: typeof GioiThieuRoute
  LienHeRoute: typeof LienHeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TinTucRoute: typeof TinTucRoute
  DichVuSlugRoute: typeof DichVuSlugRoute
  SanPhamSlugRoute: typeof SanPhamSlugRoute
  DichVuIndexRoute: typeof DichVuIndexRoute
  SanPhamIndexRoute: typeof SanPhamIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tin-tuc': {
      id: '/tin-tuc'
      path: '/tin-tuc'
      fullPath: '/tin-tuc'
      preLoaderRoute: typeof TinTucRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/du-an': {
      id: '/du-an'
      path: '/du-an'
      fullPath: '/du-an'
      preLoaderRoute: typeof DuAnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/': {
      id: '/san-pham/'
      path: '/san-pham'
      fullPath: '/san-pham/'
      preLoaderRoute: typeof SanPhamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dich-vu/': {
      id: '/dich-vu/'
      path: '/dich-vu'
      fullPath: '/dich-vu/'
      preLoaderRoute: typeof DichVuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/$slug': {
      id: '/san-pham/$slug'
      path: '/san-pham/$slug'
      fullPath: '/san-pham/$slug'
      preLoaderRoute: typeof SanPhamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dich-vu/$slug': {
      id: '/dich-vu/$slug'
      path: '/dich-vu/$slug'
      fullPath: '/dich-vu/$slug'
      preLoaderRoute: typeof DichVuSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DuAnRoute: DuAnRoute,
  GioiThieuRoute: GioiThieuRoute,
  LienHeRoute: LienHeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TinTucRoute: TinTucRoute,
  DichVuSlugRoute: DichVuSlugRoute,
  SanPhamSlugRoute: SanPhamSlugRoute,
  DichVuIndexRoute: DichVuIndexRoute,
  SanPhamIndexRoute: SanPhamIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
